version: '3'

services:

  base:
    image: base
    build:
      context: ./base
      args:
        BASE_OS: centos
        HADOOP_VER: 2.9.2
        JAVA_VER: 8

  daemon:
    image: daemon
    build:
      context: ./daemon

  namenode:
    image: daemon
    hostname: namenode
    command: start.sh hadoop namenode
    ports:
      - 50070:50070
    volumes:
      - ./daemon/format.sh:/usr/local/bin/format.sh
      - ./logs/namenode:/usr/local/apache/hadoop/logs
      - ./data/namenode:/usr/local/apache/hadoop/data/nn

  datanode1:
    image: daemon
    hostname: datanode1
    command: start.sh hadoop datanode
    ports:
      - 50075:50075
      - 8042:8042
    volumes:
      - ./logs/datanode1:/usr/local/apache/hadoop/logs
      - ./data/datanode1:/usr/local/apache/hadoop/data/dn

  datanode2:
    image: daemon
    hostname: datanode2
    command: start.sh hadoop datanode yarn nodemanager
    ports:
      - 50076:50075
      - 8043:8042
    volumes:
      - ./logs/datanode2:/usr/local/apache/hadoop/logs
      - ./data/datanode2:/usr/local/apache/hadoop/data/dn

  secondarynamenode:
    image: daemon
    hostname: secondarynamenode
    command: start.sh hadoop secondarynamenode
    ports:
      - 50090:50090
    volumes:
      - ./logs/secondarynamenode:/usr/local/apache/hadoop/logs
      - ./data/secondarynamenode:/usr/local/apache/hadoop/data/snn

  resourcemanager:
    image: daemon
    hostname: resourcemanager
    command: start.sh yarn resourcemanager
    ports:
      - 8088:8088
    volumes:
      - ./logs/resourcemanager:/usr/local/apache/hadoop/logs

  historyserver:
    image: daemon
    hostname: historyserver
    command: start.sh mr-jobhistory historyserver
    ports:
      - 19888:19888
    volumes:
      - ./logs/historyserver:/usr/local/apache/hadoop/logs

networks:
  default:
    external:
      name: hadoop